#include "file_logger.h"
#include <string.h>

#define LINCENSE "/********************************************************\n\
* this file is generated by dependence_killer,          *\n\
* it shows the dependences between files and packages   *\n\
********************************************************/\n"

FileLogger::FileLogger(const char *path) {
	m_file = fopen(path, "w");
	if(m_file) {
		fwrite(LINCENSE, strlen(LINCENSE), 1, m_file);
	}
}

FileLogger::~FileLogger() {
	if(m_file) {
		fclose(m_file);
		m_file = NULL;
	}
}

void FileLogger::Log(const char *log, size_t len) {
	if(m_file) {
		if(len > 0) {
			fwrite(log, len, 1, m_file);
		}
	}
}
